workspace:
  base: /go
  path: src/github.com/oleggator/esports-backend

pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test
  telegram:
    image: appleboy/drone-telegram
    pull: true
    secrets: [telegram_token, telegram_to]