workspace:
  base: /go
  path: src/github.com/oleggator/esports-backend

pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test
  telegram:
    image: appleboy/drone-telegram
    token: echo $telegram
    to: echo $user