CREATE EXTENSION IF NOT EXISTS citext;
CREATE PUBLICATION pub;

CREATE TABLE IF NOT EXISTS Teams (
  id      BIGSERIAL NOT NULL PRIMARY KEY,
  slug    CITEXT UNIQUE,
  title   TEXT UNIQUE,
  country CHAR(2) DEFAULT 'NO'
);
ALTER PUBLICATION pub ADD TABLE Teams;

CREATE TABLE IF NOT EXISTS Players (
  id       BIGSERIAL NOT NULL PRIMARY KEY,
  fullname TEXT,
  nickname CITEXT    NOT NULL UNIQUE,
  country  CHAR(2) DEFAULT 'NO',
  teamSlug CITEXT NOT NULL,
  team     BIGINT REFERENCES Teams (id) ON DELETE CASCADE
);
ALTER PUBLICATION pub ADD TABLE Players;

CREATE TABLE IF NOT EXISTS Games (
  id    BIGSERIAL   NOT NULL PRIMARY KEY,
  slug  CITEXT      NOT NULL UNIQUE,
  title TEXT UNIQUE NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS games_slug_idx
  ON Games (slug);
ALTER PUBLICATION pub ADD TABLE Games;

CREATE TABLE IF NOT EXISTS Tournaments (
  id     BIGSERIAL NOT NULL PRIMARY KEY,
  title  TEXT UNIQUE,
  slug   CITEXT    NOT NULL UNIQUE,
  stages JSONB
);
ALTER PUBLICATION pub ADD TABLE Tournaments;

CREATE TABLE IF NOT EXISTS Matches (
  id         BIGSERIAL                NOT NULL PRIMARY KEY,
  title      TEXT UNIQUE,
  slug       CITEXT                   NOT NULL UNIQUE,
  team1      BIGINT                   NOT NULL REFERENCES Teams (id) ON DELETE CASCADE,
  team2      BIGINT                   NOT NULL REFERENCES Teams (id) ON DELETE CASCADE,
  tournament BIGINT REFERENCES Tournaments (id) ON DELETE CASCADE,
  date       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
ALTER PUBLICATION pub ADD TABLE Matches;
